spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/telemetry/{application}
            - classpath:/config/commerce/{application}
      fail-fast: true
      retry:
        useRandomPolicy: true
        maxInterval: 6000

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/