server:
  port: 0

spring:
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/shopping-cart
    username: shopping-cart
    password: shopping-cart
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    feign: DEBUG
    ru.yandex.practicum.shoppingstore: DEBUG
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
      hibernate:
        SQL: DEBUG
        cloud.openfeign: DEBUG