spring:
  application:
    name: collector

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

grpc:
  server:
    port: 59091
    reflection-service-enabled: true

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "telemetry.collector"
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
        linger.ms: 0
    topics:
      SENSOR_EVENTS: telemetry.sensors.v1
      HUB_EVENTS: telemetry.hubs.v1